{renumber}
{step:10}
	REM ---------------------------------------------
	REM  CASASOFT UNIFIED BITMAP VIEWER
	REM  loads .BM.PRG .SC.PRG [.CO.PRG .BG.PRG] files
	REM  generated by ImageConverter and shows
	REM  the image on the VIC-II
	REM  detects multicolor (has .CO/.BG) vs hires (no .CO/.BG)
	REM  shows a list of images found on disk (files ending
	REM  in ".BM", listed without the ".BM" suffix)
	REM  press ENTER to view another image
	REM  select 0 in the list to exit
	REM ---------------------------------------------
{nice:100}
{:start}
	IF LD=0 THEN GOSUB {:init}: ld=ld+1
	if ld=1 then {:askfile}
	IF LD=2 THEN PRINT ".";: LD=LD+1: LOAD F$+".BM",DV,1
	IF LD=3 THEN PRINT ".";: LD=LD+1: LOAD F$+".SC",DV,1
	REM --- CHECK IF MULTICOLOR: TRY TO OPEN .CO FILE ---
	IF LD>4 then {:multicolor}
	OPEN 15,DV,15,"R0:"+F$+".CO="+F$+".CO": INPUT#15,ER: CLOSE 15
	IF ER=63 THEN ld=ld+1: GOTO {:multicolor}
	
	REM --- HIRES MODE: DISABLE MULTICOLOR (MCM BIT OF $D016) ---
	gosub {:commoncfg}: POKE 53270,PEEK(53270) AND 239
	GOTO {:show}
	
{:multicolor}
	REM --- MULTICOLOR: LOAD .CO AND .BG ---
	if ld=5 then ld=ld+1: PRINT ".";: LOAD F$+".CO",DV,1
	if ld=6 then ld=ld+1: PRINT ".";: LOAD F$+".BG",DV,1
	REM --- ENABLE MULTICOLOR MODE (MCM BIT OF $D016) ---
	gosub {:commoncfg}: POKE 53270,PEEK(53270) OR 16

{:show}
	REM --- BORDER ---
	POKE 53280,0
	REM --- WAIT FOR ENTER ---
{:wait}
	GET K$:IF K$<>CHR$(13) THEN {:wait}
	REM --- RESTORE ORIGINAL CONFIGURATION ---
	POKE 53265,OB:POKE 53270,OM:POKE 53272,OP
	POKE 56576,OC:POKE 53280,OF:POKE 53281,OG
	PRINT CHR$(147)
	LD=1
	GOTO {:start}
{nice:500}
	REM ---------------------------------------------
	REM --- COMMON VIC/CIA CONFIG ---
{:commoncfg}	
	REM --- VIC BANK 3 ($C000-$FFFF) ---
	POKE 56576,PEEK(56576) AND 252
	REM --- SCREEN AT $C000 (OFFSET 0) BITMAP AT $E000 (OFFSET $2000) ---
	POKE 53272,8
	REM --- ENABLE BITMAP MODE (BMM BIT OF $D011) ---
	POKE 53265,PEEK(53265) OR 32
	RETURN
{nice:700}
	REM ---------------------------------------------
	REM --- READ DISK DIRECTORY VIA "$". EN = TOTAL FILES ---
	REM --- SCANNED (ANY NAME), NF = HOW MANY END IN ".BM" ---
	REM --- (WITHOUT THE SUFFIX), STORED INTO NM$(1..NF). ---
{:dirlist}
	EN=0
	OPEN 4,DV,0,"$"
	FOR X=1 TO 6 :GET#4,A$:NEXT  'skip first line
{:read_header_loop}	
	GET#4,A$:IF A$<>"" THEN {:read_header_loop}
{:direntry}
	print ".";
	GET#4,A$,A$ 'skip next line ptr
	IF A$="" THEN {:dirend}
	GET#4,LL$,LH$ 'get line number / file size
	GT$="": fl=0
{:dirname}
	GET#4,A$
	IF A$="" OR ST<>0 THEN {:dirchecktype}
	if A$=chr$(34) then if fl=0 then fl=1: goto {:dirname}
	if a$=chr$(34) then if fl=1 then fl=0: goto {:dirname}
	if fl=0 then {:dirname}
	GT$=GT$+A$
	GOTO {:dirname}
{:dirchecktype}
	REM --- KEEP ONLY NAMES ENDING IN ".BM" ---
	IF LEN(GT$)<3 THEN {:direntry}
	IF RIGHT$(GT$,3)<>".BM" THEN {:direntry}
	GT$=LEFT$(GT$,LEN(GT$)-3)
	EN=EN+1
	NM$(EN)=GT$
	goto {:direntry}
{:dirend}
	CLOSE 4
{nice:1500}
	REM ---------------------------------------------
	REM --- SHOW IMAGE LIST AND ASK USER TO PICK ONE ---
{:askfile}
	gosub {:header}
	PC=0
	FOR FI=1 TO EN
	PRINT FI;NM$(FI)
	PC=PC+1
	IF PC=20 THEN PC=0: PRINT "{down} MORE - PRESS A KEY";: GOSUB {:pause}
	NEXT FI
	PRINT "{down} 0 = EXIT"
{:asknum}
	SN=-1
	INPUT "{down} IMAGE NUMBER";SN
	IF SN=0 THEN PRINT CHR$(147): END
	IF SN<1 OR SN>EN THEN {:asknum}
	F$=NM$(SN)
	PRINT "{down} LOADING.";
	LD=2
	goto {:start}
{nice:2000}
	REM ---------------------------------------------
	REM --- WAIT FOR A KEYPRESS ---
{:pause}
	GET K$
	IF K$="" THEN {:pause}
	RETURN
	
	REM --- PRINT HEADER ---
{:header}
	PRINT "{clear}{down} CASASOFT BITMAP VIEWER{down}": return
	
{nice:3000}
	REM ---------------------------------------------
	REM --- ONE-TIME INIT ---
{:init}
	DV=8: REM disk device number
	REM --- SAVE ORIGINAL VIC/CIA CONFIGURATION ---
	OB=PEEK(53265):OM=PEEK(53270):OP=PEEK(53272)
	OC=PEEK(56576):OF=PEEK(53280):OG=PEEK(53281)
	DIM NM$(144): EN=0
	
	REM --- READ DIRECTORY ---
	gosub {:header}
	PRINT " READING DIRECTORY"
	GOSUB {:dirlist}
	IF EN>0 THEN RETURN
	PRINT "{down} NO .BM IMAGES FOUND"
	PRINT "{down} PRESS A KEY TO EXIT";
	GOSUB {:pause}
	PRINT CHR$(147)
	END
	

