{renumber}
{step:10}
	REM ---------------------------------------------
	REM  CASASOFT UNIFIED BITMAP VIEWER
	REM  loads .BM.PRG .SC.PRG [.CO.PRG .BG.PRG] files
	REM  generated by ImageConverter and shows
	REM  the image on the VIC-II
	REM  detects multicolor (has .CO/.BG) vs hires (no .CO/.BG)
	REM  press ENTER to view another image
	REM  press ENTER on empty name to exit
	REM ---------------------------------------------
{nice:100}
{:start}
	IF LD=0 THEN GOSUB {:init}: GOSUB {:askfile}
	IF LD=1 THEN PRINT ".";: LD=LD+1: LOAD F$+".BM",DV,1
	IF LD=2 THEN PRINT ".";: LD=LD+1: LOAD F$+".SC",DV,1
	REM --- CHECK IF MULTICOLOR: TRY TO OPEN .CO FILE ---
	IF LD>3 then {:multicolor}
	OPEN 15,DV,15,"R0:"+F$+".CO="+F$+".CO": INPUT#15,ER: CLOSE 15
	IF ER=63 THEN ld=ld+1: GOTO {:multicolor}
	REM --- HIRES MODE: DISABLE MULTICOLOR (MCM BIT OF $D016) ---
	gosub {:commoncfg}: POKE 53270,PEEK(53270) AND 239
	GOTO {:show}
{:multicolor}
	REM --- MULTICOLOR: LOAD .CO AND .BG ---
	if ld=4 then ld=ld+1: PRINT ".";: LOAD F$+".CO",DV,1
	if ld=5 then ld=ld+1: PRINT ".";: LOAD F$+".BG",DV,1
	REM --- ENABLE MULTICOLOR MODE (MCM BIT OF $D016) ---
	gosub {:commoncfg}: POKE 53270,PEEK(53270) OR 16
{:show}
	REM --- BORDER ---
	POKE 53280,0
	REM --- WAIT FOR ENTER ---
{:wait}
	GET K$:IF K$<>CHR$(13) THEN {:wait}
	REM --- RESTORE ORIGINAL CONFIGURATION ---
	POKE 53265,OB:POKE 53270,OM:POKE 53272,OP
	POKE 56576,OC:POKE 53280,OF:POKE 53281,OG
	PRINT CHR$(147)
	LD=0
	GOTO {:start}
{nice:300}
	REM ---------------------------------------------
	REM --- COMMON VIC/CIA CONFIG ---
{:commoncfg}	
	REM --- VIC BANK 3 ($C000-$FFFF) ---
	POKE 56576,PEEK(56576) AND 252
	REM --- SCREEN AT $C000 (OFFSET 0) BITMAP AT $E000 (OFFSET $2000) ---
	POKE 53272,8
	REM --- ENABLE BITMAP MODE (BMM BIT OF $D011) ---
	POKE 53265,PEEK(53265) OR 32
	RETURN
{nice:500}
	REM ---------------------------------------------
	REM --- ONE-TIME INIT ---
{:init}
	DV=8: REM disk device number
	REM --- SAVE ORIGINAL VIC/CIA CONFIGURATION ---
	OB=PEEK(53265):OM=PEEK(53270):OP=PEEK(53272)
	OC=PEEK(56576):OF=PEEK(53280):OG=PEEK(53281)
	RETURN
{nice:700}
	REM ---------------------------------------------
	REM --- ASK FOR FILENAME ---
{:askfile}
	PRINT "{clear}{down} CASASOFT BITMAP VIEWER"
	PRINT "{down}{down} (NO EXT, ENTER=EXIT){up}{up}"
	F$="": INPUT " IMAGE NAME";F$
	IF F$="" THEN PRINT CHR$(147): END
	PRINT "{down}{down}LOADING.";
	LD=1
	RETURN